---
# Tasks to complete before running roles
- hosts: localhost
  tags: always
  connection: local
  become: true
  pre_tasks:
  - name: pre-run | update package cache (arch)
    tags: always
    pacman: update_cache=yes
    changed_when: False
    when: ansible_distribution == "Archlinux"

  tasks:
  - name: install packages
    package:
      name:
        # - acpilight 
        - gtop
        # - fish
        # - kitty  
        # - neovim
        # - npm
        # - python-pip
        # - ranger
        # - rofi
        # - slack-desktop
        # - spotify
        # - stow
        # - ttf-jetbrains-mono
